### ISSUE TITLE
Can't load package from src, VERSION is undefined

### ISSUE THREAD

**Issue by vinerz** [Akryum/vue-virtual-scroller#102]
Hello! I was doing a build analysis and found that `vue-virtual-scroller` built versions have some bloat overhead created by Rollup.

We can check that the `.vue` elements are in fact inlined, with comments and everything.
https://github.com/Akryum/vue-virtual-scroller/blob/7fcd54355afd7dd38590510b441d8d29ab5a6f19/dist/vue-virtual-scroller.esm.js#L1026

I was able to load it from source and build using my own scripts, but I need to remove the VERSION reference before as Rollup is responsible for replacing it at its build stage.

Doing this way, I was able to reduce the bundled package size by over **50%!** (8.5kb gizip vs 4.02kb).
Is it possible to change the way this VERSION variable is replaced so I can use the element from its source?

Thanks!

**Comment by Akryum** [comment]
The latest versions of built files don't appear to have this issue anymore.
