### ISSUE TITLE
Only first item is displayed

### ISSUE THREAD

**Issue by vladL2C** [Akryum/vue-virtual-scroller#103]
I am trying to use this library but having a hard time as it only renders the first item in the list and have no idea as to why this is happening.

This is the jsFiddle link: http://jsfiddle.net/6j4r9qoy/4/

**Comment by danshaya** [comment]
you'll need to add id to your list: http://jsfiddle.net/7t6y2qep/

Alternatively, you could specify your own unique field using keyField: http://jsfiddle.net/1kbmr49h/

**Comment by vladL2C** [comment]
Thanks very much!

**Comment by gauravalgo** [comment]
thanks you very much
