### ISSUE TITLE
DynamicScroller with pageMode

### ISSUE THREAD

**Issue by tibineagu** [Akryum/vue-virtual-scroller#111]
I'm trying to use the `DynamicScroller` in `pageMode`, but when one of the elements in the list changes size, the `ResizeObserver` keeps firing the `notify` event, which leads to an infinite loop of height recalculations <=> resize event <=> `onScrollerResize` -> `forceUpdate` and after a while the page grinds to a halt.

Unfortunately, I could not replicate this in a test environment (used codesandbox.io with a a dataset based on the virtual scroller demo - this is much more limited in complexity than the component & html+css structure we are using).

However, I was able to track this down to [this line in `ResizeObserver.vue`](https://github.com/Akryum/vue-resize/blob/c5e0b46e227666930d75188969fe8d123ba7fed8/src/components/ResizeObserver.vue#L26), where it seems the `notify` event is being emitted for every detected "resize" of the `_resizeObject`.

But, if you debug the values of `this.$el.offsetWidth` and `this.$el.offsetHeight`, they are the same across all the occurrences of the resize event (which is really strange, and I don't have the knowledge to dig deep enough and understand why this is happening).

I have made some tests with a forked version of `vue-resize` where `notify` is only triggered if one of the dimensions has changed, and it seems to be working properly. Will open a pull request soon.

**Comment by Akryum** [comment]
It should be fixed with the new version of vue-resize.
