### ISSUE TITLE
SSR with DynamicScroller

### ISSUE THREAD

**Issue by amirmasoud** [Akryum/vue-virtual-scroller#112]
When I try to use DynamicScroller in SSR mode it throws `document is not defined`, is there any way to fix it?

**Comment by evollhhan** [comment]
There is no document or window object in node env. For me, i store the data and only render the list when the page is loaded

**Comment by amirmasoud** [comment]
like `no-ssr` mode in `nuxt`?

**Comment by evollhhan** [comment]
yes.
If your list need seo, you can try to render the list with RecycleScroller or other scroller component in the ssr mode and replace it with DynamicScroller when the page is loaded.
It's a solution but I think there is a better way to deal with this situation.
