### ISSUE TITLE
Can I submit a PR for horizontal scroll ?

### ISSUE THREAD

**Issue by davestewart** [Akryum/vue-virtual-scroller#117]
I've had a brief look through the code, and it seems that it wouldn't be too difficult to support horizontal scrolling, unless there are any technical reasons, of course, as browsers default to vertical.

I propose:

- adding a new prop `direction` to take `vertical | horizontal`
    - alternatively, `axis` to take `x | y`
- modifying anything to do with `height` to `size`
- adding computed properties for internals which depending on `direction` return the right values for:
    - `height` or `y` 
    - `width` or `x` 

I'm happy to start this tomorrow as I think it would be the solution to an issue I have right now on a live project.

Would this be OK @Akryum ?

**Comment by Akryum** [comment]
Sounds good! 👍

**Comment by davestewart** [comment]
Great! Are there any contribution guidelines?

- tests
- docs
- style

?

**Comment by davestewart** [comment]
Argh! Turns out the severe jankiness was because of some kind of CSS issue to do with position: fixed and overflow:scroll on a ancestor parent. I ended up solved this after doing a ton of work to remove computed props and convert components to functional components (which didn't help that much) !

Anyway, all much better now, but I'll still have a crack at this I need a break from the project :P

**Comment by Akryum** [comment]
As the docs says, it's not necessary to use functional components (and it can even lead to worse performance).

**Comment by davestewart** [comment]
Yeah, I wanted to try everything though, and I'm not that experienced in functional components so thought it was worth trying. Also found a very interesting Quasar issue covering lots of performance tests. Anyway, good investigatory learning curve for me, and now your advice too :)

**Comment by irrg** [comment]
@davestewart any chance you're still gonna PR this? I'm about to start on table-esque horizontal scroller and was super pleased with this project's performance on my last heavy vertical scroller needs.

**Comment by davestewart** [comment]
Hey @irrg, I've just didn't have any need in the end!

**Comment by irrg** [comment]
That's a shame. Thanks for the fast reply, though!

**Comment by Akryum** [comment]
Sorry, this issue passed under my radar when I release [1.0.0-rc.1](https://github.com/Akryum/vue-virtual-scroller/releases/tag/v1.0.0-rc.1).
