### ISSUE TITLE
Blurred text with DynamicScrollerItem

### ISSUE THREAD

**Issue by babsley** [Akryum/vue-virtual-scroller#118]
Cause of this issue is too high number accuracy `transform: translateY(48.4844px);`  ![image](https://user-images.githubusercontent.com/11501912/51116009-e1526300-181a-11e9-9d50-42a8980ea930.png). I've added Math.round(size.height) for DynamicScrollerItem 145 line
 and it solved my problem

**Comment by Aterr** [comment]
@babsley could you kindly give more info about how to achieve that ? I face same thing.

**Comment by luoxiaowang** [comment]
remove  will-change: transform
