### ISSUE TITLE
DynamicScroller trigger resize

### ISSUE THREAD

**Issue by user1232324343** [Akryum/vue-virtual-scroller#119]
I saw that the DynamicScroller elements are recalculated after window size change, so I wonder is there a possibility to trigger the resize by calling a function?
Because in my case I want to change the size of an item in the DynamicScroller after it has already been rendered (for example "show more" feature).
Or do I only have the `size-dependencies` option to trigger a resize?

**Comment by Akryum** [comment]
Use `size-dependencies`. For example, if your item has a `showMore` boolean data property:

```vue
<DynamicScrollerItem :size-dependencies="[item.showMore]" ...>
```

**Comment by BusyHe** [comment]
it not worker.

```
<div class="container">
            <DynamicScroller
                ref="scroller"
                :items="list"
                :min-item-size="64"
                class="scroller"
                @resize="scrollToBottom">
                <DynamicScrollerItem
                    slot-scope="{ item, index, active }"
                    :item="item"
                    :size-dependencies="[control.expansion]"
                    :active="active"
                    :data-index="index">
                    <message
                        :msg="item"
                        :expansion="control.expansion"
                        :title="item.title"
                        :type="item.key"/>
                </DynamicScrollerItem>
            </DynamicScroller>
        </div>
```
![image](https://user-images.githubusercontent.com/17348825/94429578-1a845f80-01c5-11eb-9231-98b274db83ce.png)

**Comment by ToddliuTW** [comment]
is this issue solved? I've encountered the same issue, the value in size-dependencies has been changed, but other items doesn't resize at all
