### ISSUE TITLE
Items are not shown during scroll in firefox

### ISSUE THREAD

**Issue by vlaaadislav** [Akryum/vue-virtual-scroller#120]
Is there anything we can do?
![image](https://user-images.githubusercontent.com/28632745/51667007-d947af80-1fe0-11e9-9c05-8c9d6282d20f.png)

**Comment by Akryum** [comment]
I don't think we can do anything, as it doesn't seem there is a way to hook into the asynchronous scrolling rendering implemented in Firefox.

**Comment by Akryum** [comment]
One possible solution would be to re-implement the whole scrolling logic but that's something I'm trying to stay away from.

**Comment by SparrowBlaze** [comment]
I have a similar issue in Cordova for iOS. As I scroll, the visible items window don't seem to update until the list stops moving. Somewhat annoying...

**Comment by stalniy** [comment]
Can this be handled with touchmove/mousemove?
