### ISSUE TITLE
Vue 2.6.6 breaks this library

### ISSUE THREAD

**Issue by buremba** [Akryum/vue-virtual-scroller#128]
In 0.12.2, the tag name was different so I updated it to `recycle-scroller` for 1.0.0-beta.5. Here is how it looks like currently:
```
<recycle-scroller :item-height="240" :items="filteredData" class="scroller">
            <template slot-scope="{ item }">
              <el-card class="item" shadow="never" >
                <relation-info :active-column="item" />
              </el-card>
            </template>
</recycle-scroller>
```

And here is the screencast: https://cl.ly/60f952b442d3

P.S: We use Nuxt 2.4.2.

**Comment by buremba** [comment]
Actually, it looks like 0.12.2 is also broken now. See: https://cl.ly/efa8049aac66 All the items are rendered in default mode and using `buffer` doesn't make any difference.

Looking at the issues in the other library (https://github.com/tangbc/vue-virtual-scroll-list/issues/84) and (https://github.com/tangbc/vue-virtual-scroll-list/issues/85) I believe that this commit (https://github.com/tangbc/vue-virtual-scroll-list/issues/84#issuecomment-461766671) also broke this library. Any thoughts @Akryum ?

**Comment by buremba** [comment]
Is this issue specific to me? I have looked into the codebase but since I'm not familiar with the internals  I couldn't figure out about how to solve the issue.
If it's specific to me, I probably need to deep dive in order to be able to find a workaround.

**Comment by Akryum** [comment]
I can't reproduce with the demos.

**Comment by buremba** [comment]
@Akryum thanks for looking into the issue. Here it is: https://github.com/buremba/virtual-scroll-bug

**Comment by Akryum** [comment]
I fixed it in your repo with a simple `key-field="a"` on `<RecycleScroller>`.
