### ISSUE TITLE
Can I use computed properties?

### ISSUE THREAD

**Issue by s0updev** [Akryum/vue-virtual-scroller#129]
I need computed properties for items.
As I understand I have to stick with methods for now?

**Comment by s0updev** [comment]
Just realized that I can't use methods either because items in the DynamicScrollerItem scope.
Is it possible to transform items after sending them to DynamicScroller?

**Comment by Akryum** [comment]
You can use a component in the DynamicScrollerItem.

**Comment by s0updev** [comment]
Oh, right. Thank you
