### ISSUE TITLE
idea: buffer items & pool updates

### ISSUE THREAD

**Issue by tonypee** [Akryum/vue-virtual-scroller#13]
I've been playing with rendering items offscreen, and not updating until a certain number need updating - as i am finding that when you scroll quickly, my items do not render in time (they are more complex than just a piece of text)

this is the idea 

```
    updateVisibleItems () {
      const l = this.items.length
      const scroll = this.getScroll()
      if (scroll) {
        let buffer = 20
        let poolSize = 5
        let startIndex = Math.floor((Math.floor(scroll.top / this.itemHeight) - buffer) / poolSize) * poolSize
        let endIndex = Math.floor((Math.ceil(scroll.bottom / this.itemHeight) + buffer) / poolSize) * poolSize
```

the code was suprisingly simple - have a play and see how it feels for you

**Comment by Akryum** [comment]
Implemented in `0.6.1`
