### ISSUE TITLE
Error in DynamicScroller after 1.0.0-beta.7

### ISSUE THREAD

**Issue by tibineagu** [Akryum/vue-virtual-scroller#132]
With [this change](https://github.com/Akryum/vue-virtual-scroller/commit/a176acaf91e4a23bf5b04a469e8cff807384b855#diff-a11529d99967a81d7d8b1eb876ab4ca0R6) released in [1.0.0-beta.7](https://github.com/Akryum/vue-virtual-scroller/releases/tag/v1.0.0-beta.7) the `keyField` property is now being passed on to `RecycleScroller`.

However, the list of prepared elements being sent in the `items` prop to `RecycleScroller` [uses `id` as the `keyField`](https://github.com/Akryum/vue-virtual-scroller/blob/b5e78459dd60090ffc59ebc2ae0ec61d60425a30/src/components/DynamicScroller.vue#L90-L93), so passing a different string will break the use-case.

I think the entire line should be removed, since `RecycleScroller` defaults to `keyField = 'id'`

**Comment by tibineagu** [comment]
**UPDATE** - I've opened PR #133 to fix this if you agree it's the proper solution

**Comment by Akryum** [comment]
Oops :D
