### ISSUE TITLE
  v-slot can only be used on components or <template>.

### ISSUE THREAD

**Issue by elalienx** [Akryum/vue-virtual-scroller#134]
Hi, I have trouble using the component on Vue CLI 3.0 with Typescript. I can't compile because the error:   v-slot can only be used on components or <template>. appears

**Comment by elalienx** [comment]
Hi I answered my own question. To use in my setup I used:
`    <RecycleScroller class="scroller" :items="test" :item-size="32" key-field="id">
      <template v-slot="{ item }">
        <div class="user">{{ item.name }}</div>
      </template>
    </RecycleScroller>`

**Comment by rebz** [comment]
Worth updating the README to reflect this otherwise it may confuse others initially.

**Comment by gopala000** [comment]
Example for RecycleScroller in README does not work. Followed @elalienx  snippet. Now it renders but displays  only 22 items, even though there are 100s of items. Scrollbar does appear but shows white screen after 22 items. Below is the template I used. Appreciate if anyone can help. 

<template>

    <RecycleScroller page-mode class="scroller"
                     :items="items"
                     :item-size="32"
                     key-field="_id">
        <template #before>
            Hey! I'm a message displayed before the items!
        </template>
        <template v-slot="{ item }">
            <div class="user">{{ item.name }}</div>
        </template>
    </RecycleScroller>

</template>
