### ISSUE TITLE
Since 1.0.0-beta.6 library is built with vue@2.6 which breaks backwards compatibility

### ISSUE THREAD

**Issue by tibineagu** [Akryum/vue-virtual-scroller#136]
[See this line in `yarn.lock`](https://github.com/Akryum/vue-virtual-scroller/blame/master/yarn.lock#L5091)

The library lists `vue@2.5.21` [as a peer dependency](https://github.com/Akryum/vue-virtual-scroller/blob/112a66e9a9bc35b375df770aef7da223aaa6aa64/package.json#L41) but because it was built with `2.6.6` I think the slot behaviour has become incompatible and you get errors like in the image below.

I tried loading the components directly from `node_modules/vue-virtual-scroller/src/components/` and, when compiled locally with my version of `vue@2.5.21` it works without a hitch.

Any way you can revert to vue 2.5 to preserve backwards compatibility?

[Reproduced in this sandbox](https://codesandbox.io/s/y35y726y11)

![image](https://user-images.githubusercontent.com/441717/53156052-1d6da600-35c7-11e9-9930-820c8f392d13.png)

**Comment by asafyish** [comment]
Can I still use vue 2.6 in my project, while using the latest virtual-scroller version ?

**Comment by Akryum** [comment]
Yes

**Comment by linxian1998** [comment]
my vue version is 2.5.2 can i use the latest version of vue-virtual-scroll，if it is not, which one i can, help！！！
