### ISSUE TITLE
Virtual scrolling element-ui el-table

### ISSUE THREAD

**Issue by albert-kam** [Akryum/vue-virtual-scroller#15]
Is it possible to virtually scroll [el-table](http://element.eleme.io/#/en-US/component/table) without having to modify el-table's template source ? Has anyone attempted this before ?

**Comment by mccxiv** [comment]
I'd be interested in this too. I'm guessing it's not possible. Or did you find a solution?

**Comment by albert-kam** [comment]
Unfortunately no, so i'll just use paging on my grid ..
