### ISSUE TITLE
simple sample - beta.2 vs rc.2

### ISSUE THREAD

**Issue by Den2016** [Akryum/vue-virtual-scroller#155]
http://jsfiddle.net/marsden/9p2ht0v5/11/ - sample with beta.2 - it`s OK

http://jsfiddle.net/marsden/9p2ht0v5/13/ - sample with rc.2 - don`t work
why?

**Comment by texh** [comment]
https://jsfiddle.net/L4sgw3dv/

Check the release notes for v1.0.0-rc.1 "**BREAKING CHANGES**" here:
https://github.com/Akryum/vue-virtual-scroller/releases

**Comment by Den2016** [comment]
Thank you, was inattentive ))
