### ISSUE TITLE
Something unexpected will happen when I scroll the scroll  bar to bottom.

### ISSUE THREAD

**Issue by ZhenZY** [Akryum/vue-virtual-scroller#159]
I set up paging to get data.
Code example that works:
```
handleScroll(e) {
        const { target } = e;
        const currentScroll = target.scrollTop;
        const scrollableDistance = Math.max(0, target.scrollHeight - target.offsetHeight);
        if (currentScroll >= scrollableDistance - this.LOAD_THRESHOLD_PX) {
        if (this.hasMore) {
          this.loadMore();
      }
   }
}
```
When I scroll the scroll bar to the bottom, a blank area appears as shown in the figure.I don't know what the problem is.
![image](https://user-images.githubusercontent.com/25266953/54115340-37144780-4427-11e9-9a15-be37a26a62ce.png)

**Comment by Akryum** [comment]
I guess you didn't include vue-virtual-scroller CSS in your app.

**Comment by ZhenZY** [comment]
Yes, you're right.Thanks~
