### ISSUE TITLE
Add before-items / after-items

### ISSUE THREAD

**Issue by AshDevFr** [Akryum/vue-virtual-scroller#16]
First, I'd like to say this component is great.

I would like to know if you could consider the option to add custom items before and after the item list.

My use case is that sometime in a list for example, I have a loading item in the end of the list. 

If I add it in the after-content it will be outside of my UL and won't be seen as it won't be counted in the total height. 

Here you don't add the before/after-content height: https://github.com/Akryum/vue-virtual-scroller/blob/master/src/components/VirtualScroller.vue#L164

We could also fing a way to say "I have 80 extra pixel you have to add"

**Comment by AshDevFr** [comment]
It is really a dirty draft but something like that : https://github.com/AshDevFr/vue-virtual-scroller/blob/before_after-items/src/components/VirtualScroller.vue

**Comment by Akryum** [comment]
You can dynamically add the item to the items list.
