### ISSUE TITLE
"Unexpected token import" when trying to import into a Meteor project

### ISSUE THREAD

**Issue by Herteby** [Akryum/vue-virtual-scroller#17]
I wanted to try it out in my Meteor project but I get this error:

"Uncaught SyntaxError: Unexpected token import"
node_modules/vue-virtual-scroller/src/index.js Line 1:
***import*** _VirtualScroller from './components/VirtualScroller.vue'

So somehow it's not using ES6 or something? Got any ideas?

**Comment by Akryum** [comment]
Please refer to the [vue-meteor documentation](https://github.com/Akryum/vue-meteor/tree/master/packages/vue-component#using-vue-npm-packages) and use [compiled files](https://github.com/Akryum/vue-virtual-scroller#distribution-import).

**Comment by Herteby** [comment]
Ah okay, thanks :sweat_smile:
