### ISSUE TITLE
Blank areas in the project

### ISSUE THREAD

**Issue by ZhenZY** [Akryum/vue-virtual-scroller#175]
As shown in the figure，I don't know what caused the blank areas in the project.
![image](https://user-images.githubusercontent.com/25266953/55156727-99927500-5195-11e9-9732-e9816e740c6d.png)
This is the code I wrote.
（GetNoticeList is a computed property）
```
<DynamicScroller
      :items="getNoticeList"
      class="notice-list__scroller"
      :min-item-size="45"
      @scroll.native.passive="handleScroll"
      key-field="announce_id">
      <template v-slot="{ item, index, active }">
        <DynamicScrollerItem
          :item="item"
          :active="active"
          class="notice-list__item"
          :watchData="true"
         :size-dependencies="[item.title, item.content_detail]">
          <notice-item
            :notice="item"
            :index="index"
            :key="item.announce_id"
            v-contextmenu:contextmenu
            @cancleMenucontext="cancleMenucontext"
            :isRightMenuShow="isRightMenuShow"
            :isOtherSelected="isOtherSelected"
            >
          </notice-item>
        </DynamicScrollerItem>
      </template>
</DynamicScroller>
```
![image](https://user-images.githubusercontent.com/25266953/55158984-1d9b2b80-519b-11e9-8a6b-9603240dda79.png)

**Comment by texh** [comment]
@ZhenZY Did you include the required CSS? https://github.com/Akryum/vue-virtual-scroller#default-import

Those negative style values you've highlighted are probably normal 😸

**Comment by ZhenZY** [comment]
Yes,I've introduced CSS， but there's still a problem.

**Comment by ZhenZY** [comment]
I see.The keyField binds a duplicate value.

**Comment by pangu663** [comment]
> 我明白了.keyField绑定了一个重复的值。

没太懂，留下联系方式，打款，哈哈，，真没懂:key？:data-index？都改成时间了，还是空白

**Comment by ZhenZY** [comment]
> > 我明白了.keyField绑定了一个重复的值。
> 
> 没太懂，留下联系方式，打款，哈哈，，真没懂:key？:data-index？都改成时间了，还是空白

You can send me your contact information and I may be able to help you.

**Comment by pangu663** [comment]
> > > 我明白了.keyField绑定了一个重复的值。
> > 
> > 
> > 没太懂，留下联系方式，打款，哈哈,,真没懂：关键：？？数据索引都改成时间了，还是空白
> 
> 您可以将您的联系信息发送给我，我也许可以帮助您。

weixin：weibu7374520
