### ISSUE TITLE
Cannot get it to work at all

### ISSUE THREAD

**Issue by DenisNP** [Akryum/vue-virtual-scroller#177]
Hello there. I think I am doing something totally wrong.

This is my code inside complex html page:
``` vue
<RecycleScroller v-if="currentList.length"
    :items="currentList"
    :item-size="73"
    key-field="id"
>
    <div
        v-slot="{ item }"
    >{{ item.title }}</div>
</RecycleScroller>
```

I am pretty sure that I installed and connected library correctly. Also my Vue version is `3.3.0`. 

`currentList` is an array of objects like:
``` javascript
[
  {
    id: 1,
    title: 'ABC',
  },
  {
    id: 2,
    title: 'BCD',
  }
]
```
But when I am runnig code I get bunch of errors:
`[Vue warn]: Property or method "item" is not defined on the instance but referenced during render.`
And
`Failed to resolve directive: slot`

So, is there any complete example of how to use scroller?

**Comment by amatakasap** [comment]
Try it

```
v-slot = "{item, index, active}"
```

**Comment by DenisNP** [comment]
Undortunately, it didn't help. Is there any source code for demo?

**Comment by DenisNP** [comment]
Okay, my fault. There was `vue 3.3.0` globally inside my system, but on project was only `2.5.1`. So `v-slot` introduced since `2.6.0`. Updated and it works, thanks!
