### ISSUE TITLE
Disable Hover

### ISSUE THREAD

**Issue by errrken** [Akryum/vue-virtual-scroller#178]
Hi,

I am doing a 2D grid, with a lot of mouse interactions. I notice a there is a mouseenter and mouseleave event attached for the hover class, which affects the performance a lot. Is it possible to disable these events somehow? 

I am trying to stop the propagations but does not seem to work:
`<template slot-scope="{ item, index }">
          <div
            @mouseleave.stop.prevent
            @mouseenter.stop.prevent></div>
</template>`

Thanks

**Comment by TheTrueRandom** [comment]
yes please, it is adding a lot of lag: 

![image](https://user-images.githubusercontent.com/43322965/80925272-aa48ed80-8d8e-11ea-8b1d-344223ccf6bb.png)

**Comment by slidenerd** [comment]
```
.vue-recycle-scroller__item-view .hover {
  background: none;
}
```

does not work

**Comment by jibow** [comment]
When hovering over the items every component defined in the default slot gets updated which slows down performance significantly. I was able to fix this issue by extracting the components I previously defined in the slot to a single component. Then only this component gets updated. This increased my performance by a factor in the thousands.

**Comment by ishitatsuyuki** [comment]
Can anyone try if #742 fixes your issue? If you are using yarn you can install it by putting the following in your package.json.
```
    "vue-virtual-scroller": "npm:@ishitatsuyuki/vue-virtual-scroller@2.0.0-alpha.a2f6a94",
```

cc @Bluskript @EricRabil @AMontagu @YoungL1107

**Comment by gans-groover** [comment]
Hi, @ishitatsuyuki I've created this pull request as your version seems to be meant for Vue3 : https://github.com/Akryum/vue-virtual-scroller/pull/752
