### ISSUE TITLE
Custom scrollbar 

### ISSUE THREAD

**Issue by kovart** [Akryum/vue-virtual-scroller#18]
Is it possible to use custom scrollbar with JS animation of scrolling?

**Comment by adavidof** [comment]
@Akryum 
friendly ping

I need custom scrollbar. Thanks

**Comment by EugeneBalabai** [comment]
@kovart @davydof how did you solve the problem?

**Comment by davydof** [comment]
@EugeneBalabai switched to React

**Comment by lchxiang** [comment]
I need this please

**Comment by SimonPreini** [comment]
I also need a solution for this😅
