### ISSUE TITLE
Injection "vscrollData" not found

### ISSUE THREAD

**Issue by shenyong11** [Akryum/vue-virtual-scroller#192]
Why is that?

Injection "vscrollData" not found

Injection "vscrollParent" not found

Cannot read property 'simpleArray' of undefined

**Comment by Amersfoj** [comment]
Did you find a solution for this? I have the same problem. Passing a `vscroll-data` prop to the DynamicScroller does not work either.

**Comment by hzz07** [comment]
Did you find a solution for this? I have the same problem. Passing a vscroll-data prop to the DynamicScroller does not work either.
