### ISSUE TITLE
Variable Height

### ISSUE THREAD

**Issue by Textras** [Akryum/vue-virtual-scroller#20]
"You need to set the size of the virtual-scroller element and the items elements (for example, with CSS). All items should have the same height to prevent display glitches."

On the hunt for a solution with variable height components. Using templates and even looking at a RecyclerView with tombstones is fine and dandy till you are confronted with the myriad of various sized components often found in a feed. 

Still trying to gather best practices regarding variable height implementation. Wonder if you have any unique takes or are interested in adding the functionality here. Calculating the height of all indexed items in an array pre-render seems to be a method, a getRowHeight callback another option but neither are ideal.

**Comment by asafyish** [comment]
I agree.
Even the simplest use case, of rows separated by some kind a title, won't work without dynamic height.

**Comment by Akryum** [comment]
This was an design choice made to get the best performance possible, but I might investigate variable height in the future.

> Even the simplest use case, of rows separated by some kind a title, won't work without dynamic height.
You can put a title with the same height :smile:

**Comment by Textras** [comment]
@Akryum Thanks for the response. I have really done a lot of searching, far and wide. Days worth. If you look into the issues of the RecyclerView plugin, and a few other infinity (virtual) scrolls you might see similar inquiries. I guess what I'm saying is adding variable heights into this component would be huge for it's adoption and likely make it the only (or one of the only) components suitable for a 'feed' style use case. :D

**Comment by Akryum** [comment]
This is now implemented in `0.7.1`.

**Comment by asafyish** [comment]
Amazing Job !
