### ISSUE TITLE
Is there a way to control the pool size in variable height mode ?

### ISSUE THREAD

**Issue by asafyish** [Akryum/vue-virtual-scroller#21]
I see that poolSize is calculated based on the visible screen height, is there a way to increase it ?
the use case is, when scrolling fast, I can see for a split second, a white area where rows should appear, I am guessing it's because the browser didn't have enough time to move the existing rows to that location.

It's not critical, We are already seeing major performance boost thanks to this great library.

**Comment by Textras** [comment]
+1

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-virtual-scroller/releases/tag/v0.10.1
