### ISSUE TITLE
Checkboxes in List don't (visually) reset 'checked' property

### ISSUE THREAD

**Issue by Arthesian** [Akryum/vue-virtual-scroller#214]
My issue is; I have a list with for example 1000 entries. Only ~20 are rendered at a time.

Each item has a checkbox, with a ':checked' property bound to the item in the data list.

But if I check for example items 2 & 5, and I scroll to items 40-60, I would see 42 and 45 as 'checked' (even though when I inspect the data of the tile, their checked property is set to 'false'. 

So in the data set, the boolean is set to false, but in the 'view' the checkboxes are rendered as 'checked'.... Can someone help me with this? I don't really get why it isn't working to be honest...

**Comment by Akryum** [comment]
Hey! Thanks for your issue! Please provide some runnable minimal reproduction so I can look into this. Cheers

**Comment by Arthesian** [comment]
Sorry. When I tried to make a minimal reproduction :P I finally figured out the mistake in my own project -- haha. I used a wrong reference for the clicked object. which caused the weird behaviour.

It's working perfectly fine now -- my bad!

**Comment by avaguerrero** [comment]
@Arthesian I am having the same issue. Are you able to elaborate on having a wrong reference for the clicked object?

**Comment by Arthesian** [comment]
I'm sorry - I can't really remember the issue at hand. But I think it had something to do the setting the correct key-field to the rendered list item. If I remember correctly; in my case it wasn't a unique field because I had configured it in a wrong way -- which was causing all kinds of weird behaviour.

So please double check the uniqueness of the 'key' field for each item -
