### ISSUE TITLE
Could it works like this?

### ISSUE THREAD

**Issue by CalmHoly** [Akryum/vue-virtual-scroller#218]
https://vue-comps.github.io/vue-clusterize/#!/flex

⬆️,like this.

there are about 20000+ div(width:200px;height:200px) include <img> in my webpage...

help!!  QAQ...

waiting for some reply....

**Comment by muthu32** [comment]
Use this component https://github.com/starkwang/vue-virtual-collection for masonry

**Comment by CalmHoly** [comment]
> Use this component https://github.com/starkwang/vue-virtual-collection for masonry

thanks~
