### ISSUE TITLE
Emit start and end indexes on change, to allow database fetching

### ISSUE THREAD

**Issue by Herteby** [Akryum/vue-virtual-scroller#23]
I'm integrating this with Meteor to fetch items on-demand from the database.
When it emits an update, I update the skip and limit of the subscription.

I created a pull request here: https://github.com/Akryum/vue-virtual-scroller/pull/22

**Comment by Herteby** [comment]
I can now smoothly scroll through a 50,000 item list that is being sent from the server on demand based on scroll location! :smile:

**Comment by Akryum** [comment]
https://github.com/Akryum/vue-virtual-scroller#update-event
