### ISSUE TITLE
Customize tags

### ISSUE THREAD

**Issue by aesfer** [Akryum/vue-virtual-scroller#235]
Right now we can customize the element tags via `DynamicScrollerItem.tag` but there does not seem to be a way to customize the wrapping element tag.

This is important for accessibility reasons. In my case the elements need to be `li` and the wrapper needs to be an `ol` or at least have the attribute `role="list"`.

Browsing the repo history I saw this used to be supported via `mainTag`, `containerTag` and `contentTag`. Is this something you intend to support again?

Cheers :)

**Comment by mattgreenfield** [comment]
I too would like this. I think there might be some other accessibility concerns though as the announced length of the list will be wrong. Maybe an aria-label or aria-description would solve that.

**Comment by EricMcWinNer** [comment]
I'm actually trying to implement a virtualized table with this, and there's no way to specify that the wrapper of the virtualized list should be a table. This would be pretty awesome.

**Comment by Akryum** [comment]
Implemented

**Comment by skjnldsv** [comment]
Could we also get the root tag, so we can set a table please @Akryum ? :)
