### ISSUE TITLE
virtual-scroller's 'items' watcher isn't working

### ISSUE THREAD

**Issue by Herteby** [Akryum/vue-virtual-scroller#25]
[This one](https://github.com/Akryum/vue-virtual-scroller/blob/master/src/components/VirtualScroller.vue#L122)

It never ever executes. And I don't get why :confused:
'items' is definitely changing.

[my testing repo](https://github.com/Herteby/testing)

**Comment by Akryum** [comment]
You have an issue in your code [here](https://github.com/Herteby/testing/blob/master/client/components/infinite.vue#L26), take a look at [Vue documentation](https://vuejs.org/v2/guide/list.html#Caveats). :smile:

**Comment by Herteby** [comment]
Aaah, thanks! 😀
