### ISSUE TITLE
Margin-top of 'items' element is going to infinity

### ISSUE THREAD

**Issue by kovart** [Akryum/vue-virtual-scroller#29]
The scroller (margin-top) is going to infinity when scroll fast down by using scrollbar thumb.

**Comment by Akryum** [comment]
Do you have a repro for this?

**Comment by hotovec** [comment]
The same issue here. 

Screencast https://www.dropbox.com/s/oyubcuno2qeinwd/Infinity.mp4?dl=0

It is the first time I'm using this component. In case you scroll to the end, scrolling is not stopped, but start some infinity loop. (OSX, safari, touchpad scrolling)

I have vuex state variable with array of objects (8000 tasks)
```
data: [
    {id: 1, clientId: 'client_3', label: 'Task5', created: null, sessions: []},
    ...
  ]
```

I have getter which is filtering array of tasks and return subset of tasks by clientID
```
TasksByClientId: (state, getters) => (cid) => {
    return state.data.filter(task => task.clientId === cid)
  }
```

This getter is used this way:
```
<virtual-scroller class="scroller" :items="TasksByClientId(Globals.currentClientId)" itemHeight="30">
<template scope="props">
      <div class="scroller-cell">REC {{props.item.id}}</div>
</template>
</virtual-scroller>
```

css:
```
.scroller {
        height: 100vh; // doesn't matter, bug is here also for px value
        overflow: scroll;
    }

    .scroller-cell {
        height: 30px;
    }
```

So seems this is not some special case.

**Comment by Ayiga** [comment]
I was experiencing this too.  Make sure you're importing the css into your project:

```javascript
require('vue-virtual-scroller/dist/vue-virtual-scroller.css')
```

**Comment by hotovec** [comment]
thanks, I will try that.

**Comment by Akryum** [comment]
Please re-open if you still have the issue.
