### ISSUE TITLE
Miscalculated space between items

### ISSUE THREAD

**Issue by chrisbarton126** [Akryum/vue-virtual-scroller#299]
I'm using `DynamicScroller` and `DynamicScrollerItem` to render a list of results which are being retrieved through a polling mechanism from an API using axios and then exposed through a computed property which handles sorting and filtering. 

If all of my results load in a single poll then the list renders with absolutely no problems. However, if it takes a few polls to get a full set of results, and on each ping a get a sub-set of results then I start to see really strange behaviour where the `transform: translateY(...)` is wildly off. This leaves me with situations where there is a large gap of whitespace between the top of the container and the first result, or there is a large gap between several of the results. It doesn't matter if I start scrolling, or if the list gets recomputed several more times via filtering / sorting, it never corrects itself. 

`page-mode` is being used, and the component is output within a column. There is content at the top of the page above the results, so I'm unsure if this could be causing miscalculations when paired with `page-mode`? The application is using Vuetify throughout including for layout classes (i.e. flex, columns etc.)

```
<dynamic-scroller
    :items="handler.results"
    :min-item-size="54"
    class="scroller"
    page-mode
  >
 <template v-slot="{ item, index, active }">
   <dynamic-scroller-item :item="item" :active="active" :data-index="index">
     <accommodation-card :result="item" :key="item.id" />
   </dynamic-scroller-item>
 </template>
</dynamic-scroller>
```
![image](https://user-images.githubusercontent.com/2964041/67561389-a61f8180-f714-11e9-861c-4013af3fd381.png)

(Screenshot has had content on the left-hand side ommitted)

Any help would be greatly appreciated!

**Comment by chrisbarton126** [comment]
Ignore this, after much digging I found out that my results were unsanitised and contained duplicate id's. Solved the issue in the ajax handler and now works perfectly!

**Comment by Aterr** [comment]
Hello there @Akryum !
I have same issue, but have no possibility to fix it with ajax. Could you please guide me, what am I doing wrong ?

**Comment by chrisbarton126** [comment]
Hi @Aterr 

As mentioned in mine, the unique key being assigned to each of my elements was being duplicated. Once I removed the duplicates that resolved the issue, obviously AJAX was the means with which to fix mine, would you be able to check your data source to ensure that there are no duplicates?

**Comment by Aterr** [comment]
@chrisbarton126 
Oh my...
You were totally right. 15 minutes of debugging and viola. 
Had some duplicates in the response. Thanks a lot, you saved my ass!
