### ISSUE TITLE
Stacking context issue

### ISSUE THREAD

**Issue by kilkujadek** [Akryum/vue-virtual-scroller#319]
Hello, first of all - thank you for such a great script!

I have a little problem with using [multiselect](https://vue-multiselect.js.org) plugin together with the dynamic scroller. It renders correctly only in one direction, which depends on scrolling direction. 

I've made a simple demo, select appear is in edit mode (double click):
[https://codesandbox.io/s/z-index-issue-rxkkx](https://codesandbox.io/s/z-index-issue-rxkkx)
Check two selects at top and bottom of page - one of them will be under scroller rows.

Any suggestion of how this could be fixed?

**Comment by pleek91** [comment]
I'm also running into this same problem. I was able to hack a solution together that involved adding a `z-index` to the row the user is currently interacting with, and then removing that `z-index` when the user clicks off of that row. Basically something like this

`element.closest('.vue-recycle-scroller__item-view).style.zIndex = '1';`

Where `element` is something inside your row that the user has interacted with. You'll also need to do the inverse to remove the `z-index` when the user is done.

**Comment by ploissken** [comment]
Argh, I have been trying for 3 hours, setting z-indexes everywhere... No juice at all.
![zicauo](https://user-images.githubusercontent.com/37518433/71838874-9ae3bd00-3098-11ea-8c92-2883016fa80e.png)

**Comment by kilkujadek** [comment]
I've spend more then 3 days ;)

I've finally sort it with @AousAnwar solution:
https://github.com/Akryum/vue-virtual-scroller/pull/138

I've modify it, so every row is using `top` instead of `transform`.

**Comment by ploissken** [comment]
Sorry, I didn't understand how to apply the changes...
You got it edited outside of node_modules, as a component in your project?

**Comment by ploissken** [comment]
Finally made it work!!
Thanks @kilkujadek

**Comment by bobaoapae** [comment]
Hello, can this be merged? I have this issue here

**Comment by DGollings** [comment]
> 
> 
> I've spend more then 3 days ;)
> 
> I've finally sort it with @AousAnwar solution:
> #138
> 
> I've modify it, so every row is using `top` instead of `transform`.
@kilkujadek 
Running the @AousAnwar solution which fixes it for modals (thanks btw), but can't get it to fix my multiselect issue which I think is the same problem you had. 'Top' doesnt seem to matter. 

Could you post an code snippet of your solution? Could maybe help the barely competent at frontend dev, asking for a friend :)

**Comment by bobaoapae** [comment]
> > I've spend more then 3 days ;)
> > I've finally sort it with @AousAnwar solution:
> > #138
> > I've modify it, so every row is using `top` instead of `transform`.
> 
> @kilkujadek
> Running the @AousAnwar solution which fixes it for modals (thanks btw), but can't get it to fix my multiselect issue which I think is the same problem you had. 'Top' doesnt seem to matter.
> 
> Could you post an code snippet of your solution? Could maybe help the barely competent at frontend dev, asking for a friend :)

https://github.com/bobaoapae/vue-virtual-scroller/commit/49715a5338a09ea187e998f8092269709ed2d0af

**Comment by Akryum** [comment]
BTW, views are recycled, so their position in the HTML doesn't match their position on display.

**Comment by mohamadrezahedayati** [comment]
Hi @kilkujadek 

Like you, I had the same problem and I installed and used [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) plugin  , [multiselect ](https://vue-select.org/)plugin together.

Of course, `vue-virtual-scroller` has a problem with dropdown in terms of `z-index` and I did a lot of tests for this issue.

But this problem we have is not from `vue-virtual-scroller` plugin I think **this problem is from `multiselect` plugin** and I solved it as follows : 

You add **`append-to-body`** directive to your component ( v-select )

![image](https://user-images.githubusercontent.com/43079809/107940275-3aae9280-6f9d-11eb-8e2d-17011c214769.png)

**further reading :** [vue-select - appendToBody](https://vue-select.org/api/props.html#appendtobody)

**Comment by ahmadmu** [comment]
I'm having the same issue with vue bootstrap's `b-dropdown`, top direction works fine, the bottom doesn't. Adding a z-index to the current row as @pleek91 suggested works and puts the dropdown on top, but is there a better solution for it?

**Comment by mustafaBagwala** [comment]
@Akryum  Which version of package contain this fix please ?
