### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by amorino** [Akryum/vue-virtual-scroller#33]
I see this library render the content with height and margin-top, so the scroll is always vertical. Is horizontal scroll supported?

**Comment by Akryum** [comment]
Not yet.

**Comment by danilopolani** [comment]
+1, horizontal virtual scroll would be awesome. My table with 50 rows x 60 columns is slow also with virtual scroll.

**Comment by eaguad1337** [comment]
+1, there is any workaround?

**Comment by 7immer** [comment]
+1 for this. My use case is a horizontal scrolling calendar showing a week day view.

**Comment by Akryum** [comment]
Implemented in [v1.0.0-rc.1](https://github.com/Akryum/vue-virtual-scroller/releases/tag/v1.0.0-rc.1).
