### ISSUE TITLE
Buffer prop seems to be bugged

### ISSUE THREAD

**Issue by rogeralsing** [Akryum/vue-virtual-scroller#336]
setting buffer to a number to 500 or greater start chopping off elements from the rendered list.

My impression is that this number adds an area above and below the visible area where items are pre-rendered to avoid flickering.
But instead it seems to reduce how much is rendered when the number is bigger.

**Comment by belov91** [comment]
@rogeralsing if you are using the `DynamicScroller`, currently it has no `buffer` prop. I created a PR with a fix. https://github.com/Akryum/vue-virtual-scroller/pull/529
