### ISSUE TITLE
DOM order

### ISSUE THREAD

**Issue by ziga-miklic** [Akryum/vue-virtual-scroller#359]
Hello!

Is there a way to make sure the DOM order matches the items (data) array order? This most likely will not be as performant, but it may be relevant for some use case like ours.

We have a log viewer where the users need to copy multiple lines. The issue is that when you try to copy multiple lines, the selection jumps around due to the DOM order being different to order the user sees on the screen.

If this is currently not possible, would you consider adding this as an option? I would gladly help with the PR.

Thank you!

**Comment by Akryum** [comment]
Currently the items are reorganized for performance reasons. Also in your use case, copying multiple lines also means that if the user continue to select lines down, the previous lines will be removed anyway.

**Comment by ziga-miklic** [comment]
That is true and for copying more lines than currently displayed we intend to provide a form where the user will write the start and end line number to copy.

Most likely our users will select just a few lines, so allowing selection with the mouse is still the preferred and most intuitive solution.

We may try a solution using the `update` event to reorder the DOM ourselves and keep it depending on the performance hit.

Thank you for all your OSS contributions. Keep up the great work!

**Comment by Akryum** [comment]
I implemented a new feature that automatically sort the views depending on the items index as soon as the user stops scrolling.
