### ISSUE TITLE
Slow FPS

### ISSUE THREAD

**Issue by gkatsanos** [Akryum/vue-virtual-scroller#36]
Hello,

Could you help me out figure out why this is laggy?: https://codepen.io/jrast/pen/QqMGdR?editors=1010

**Comment by Akryum** [comment]
Try setting a poolSize value, for example 2000px.

**Comment by Akryum** [comment]
It seems you are using components that take time to render. I forked the pen and the performance is quite good for me: https://codepen.io/Akryum/pen/eGqqZL
In the future, I may create another component alongside the virtual-scroller, that will recycle components/elements and see if it can improve the performances.

**Comment by jrast** [comment]
Thanks for looking at this. Ah ok, up until now, i considered `poolSize` and `buffer` as number of elements and not pixels. As I can see, you updated the docs!

Can there anything be done at the moment to improve the speed? Using less components? Use `once` on the components where aplicable?

**Comment by Akryum** [comment]
Closing now that RecycleScroller is out.
