### ISSUE TITLE
Handle removed items from items list

### ISSUE THREAD

**Issue by talberkoSB** [Akryum/vue-virtual-scroller#360]
Hi,
I use `dynamic-scroller` with `dynamic-scroller-item`.
When an item in the list is deleted by the user, it will be destroyed, but still exists in the dom (but hidden).
If I add `v-if="active"` to the `dynamic-scroller-item`, it will be removed, but it will be relevant also for all inactive items (Which will cause a performance degradation).
My question is: how can the list be updated with a deleted list item, so it will be removed completely from the dom?

Thanks

**Comment by Akryum** [comment]
Dom nodes are not destroyed to be reused efficiently.

**Comment by talberkoSB** [comment]
@Akryum I know they are not destroyed.
What happens if the item is not in the items list anymore? why should it stay to be reused if it doesnt exist anymore?
Is the solution to add `v-if="index > -1"` to the scroller item?
