### ISSUE TITLE
DynamicScrollerItem shold be object(not array) in DynamicScroller

### ISSUE THREAD

**Issue by NikitaIT** [Akryum/vue-virtual-scroller#361]
if items `[...valuesById.entries()]` - only first item rendered.
if items `[...valuesById.entries()].map(x => ({ id: x[0], innerItem: x[1]}))` - all items rendered.
I hope I saved someone time.

**Comment by Akryum** [comment]
Here is a working example using an array of strings: https://github.com/Akryum/vue-virtual-scroller/blob/master/docs-src/src/components/SimpleList.vue
