### ISSUE TITLE
ERROR in vendor.js from UglifyJs when import vue-virtual-scroller

### ISSUE THREAD

**Issue by lizy0329** [Akryum/vue-virtual-scroller#369]
check the source [vue-virtual-scroller.min.js, vue-virtual-scroller.esm.js, vue-virtual-scroller.umd.js]

const let has not transfer to var !!!

**Comment by chaim0m** [comment]
Same issue! What can be done to get around this?

**Comment by lizy0329** [comment]
I fixed this with switching UglifyJS with TerserPlugin
https://github.com/kidjp85/react-id-swiper/issues/324#issuecomment-522525927

bug you can exclude 'vue-virtual-scroller' in node_module

**Comment by outOFFspace** [comment]
Please, fix this

**Comment by edon92** [comment]
i try to add exclude in UglifyJs,but it not works.
finnally,i add include in babel-loader.it works.

**Comment by ykamal** [comment]
Nothing's working for me. @edon92 how did you make it work?

**Comment by SmartWuJun** [comment]
他的代码 包含 es6 const 语法 需要自己转es5
