### ISSUE TITLE
Strategy for 500k+ items?

### ISSUE THREAD

**Issue by Lewenhaupt** [Akryum/vue-virtual-scroller#371]
Hi,

I have a project where we deal with a very large number of messages that we need to visualize (we're talking millions) and I wonder what the strategy would be to accomplish this with vue-virtual scroller? 

Ideally, I would want a scrollbar that would represent the total amount of items and use vue-virtual-scroller to handle the current items that are actually visible plus some for user experience. 

Any ideas?

**Comment by Akryum** [comment]
Did you try to use virtual scroller already?

**Comment by Lewenhaupt** [comment]
> 
> 
> Did you try to use virtual scroller already?

No, I just read the documentation while looking for a possible solution.
I think though that my issue is more of a UX issue rather than trying to find a tool that can support the load. So I think I'll use virtual scroller but use a paged lazyloading, because I will never be able to visualize the entire dataset with just a scrollbar as that would require the webpage to at least know an id for each, and just that could be too much.
