### ISSUE TITLE
vue-virtual-scroller.min.js use es6, cause IE error

### ISSUE THREAD

**Issue by lianzhao** [Akryum/vue-virtual-scroller#379]
There' re `cosnt` key words in `vue-virtual-scroller.min.js`. 

PS, [v1.0.0.rc2](https://github.com/Akryum/vue-virtual-scroller/blob/2194271cfe9b467d292266e8c2c6bb65bb814e4e/dist/vue-virtual-scroller.min.js) works well on IE

**Comment by Akryum** [comment]
`const` is supported by IE 11. If you need different kind of transpilation, please add the library to your babel setup (for example, using [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies) if you use vue-cli).
