### ISSUE TITLE
Keyboard support?

### ISSUE THREAD

**Issue by stefan2410** [Akryum/vue-virtual-scroller#39]
Hi!  Should not the scroller support keyboard scrolling? page, arrows?  or it is like that by  design?
If the keyboard navigation works, it is very useful component.

**Comment by Akryum** [comment]
I does support keyboard scrolling. It is just an element with `overflow-y: auto`, so if your browser supports it, it will also work for the virtual-scroller. In the demo, it doesn't scroll with the keyboard because I have set `user-select: none` on the rows.
