### ISSUE TITLE
Items in pool are not updated correctly

### ISSUE THREAD

**Issue by asafyish** [Akryum/vue-virtual-scroller#41]
Hi,

We are using this library, and we have a long list of rows,
If we modify some of the values that each row is using, it's not updated as expected.
If we scroll down, let the pool create new items, and then scroll back, the row is updated.

It looks like after the initial rows are rendered, they are not updated anymore.

It worked on version 0.10.1 and stopped working on 0.10.2.
Could be because of 
"Some unnecessary updates are now skipped."
Another piece of info: the key is not modified.

**Comment by Akryum** [comment]
Do you have a reproduction to share? My rows are getting updated.

**Comment by asafyish** [comment]
I can confirm it's fixed in version 0.10.5
