### ISSUE TITLE
Version 0.10.6 optimizations

### ISSUE THREAD

**Issue by asafyish** [Akryum/vue-virtual-scroller#42]
Hi,

Can you elaborate what optimizations you did in the 0.10.6 version ?
It's nice to learn new tricks.
I tried reading the code, but couldn't quite understand.

**Comment by Akryum** [comment]
That was mostly preventing unnecessary `updateVisibleItems` by waiting for the next Vue tick to run it. Also, the code follows the official style guide more closely now.
