### ISSUE TITLE
How to tell when end is reached?

### ISSUE THREAD

**Issue by dtruel** [Akryum/vue-virtual-scroller#43]
Hello, and thanks for all your hard work on this excellent component.

I'd like to use this in an infinite scroll capacity. Is there an event that is emitted when the end of the list is reached?

**Comment by Akryum** [comment]
Hi,
Use the standard `scroll` event and other scroll-related properties:

```html
<virtual-scroller @scroll.native="onScroll">
```

```js
el.offsetHeight + el.scrollTop >= el.scrollHeight
```

**Comment by dtruel** [comment]
@Akryum Thanks a million!  Works perfect.

**Comment by LiangNex** [comment]
> Hi,
> Use the standard `scroll` event and other scroll-related properties:
> 
> ```
> <virtual-scroller @scroll.native="onScroll">
> ```
> 
> ```js
> el.offsetHeight + el.scrollTop >= el.scrollHeight
> ```

Thanks for the tip though I spent some time struggling out the way to apply it on new component ```RecycleScroller``` 😆 
It needs to be applied on the parent dom, like this:
```
<div @scroll.native="onScroll">
    <RecycleScroller
      :items="data"
      :item-height="32"
    >
      ...your content...
    </RecycleScroller>
</div>

export default {
  ...
  methods: {
      onScroll() {
      if (this.$el.offsetHeight + this.$el.scrollTop >= this.$el.scrollHeight) {
        // your logic
      }
    }
  }
}
```

**Comment by fabdao** [comment]
VueJs and Ionic, working like a charm ! Thank guys for this sweet component !

```
<template>
    <RecycleScroller
        :items="data"
        @scroll.passive="(e:any) => onScroll(e)"
    >
        <template v-slot="{ item }">
            <CelebrityCard />
        </template>   
    </RecycleScroller>
</template>



function onScroll (event:any) {
    //End of scrolling
    if ( event.target.offsetHeight + event.target.scrollTop >= event.target.scrollHeight) {
        console.log('END');
    }
}
```
