### ISSUE TITLE
ScrollToItem error

### ISSUE THREAD

**Issue by Cxyushi** [Akryum/vue-virtual-scroller#45]
No items displayed on viewport when the method `scrollToItem(index)` called with index which is greater then twice of the page size.
The debug info in console is:
`[Vue warn]: Duplicate keys detected: ''. This may cause an update error.`

**Comment by kimond** [comment]
I get the same error while I'm trying to scroll fast to the end of the list. I think this is because the virtual scroll tries to generate all elements while scrolling. However, on my end, I have heavy components to render.

**Comment by Cxyushi** [comment]
I find that the problem is caused by the variable `keysEnabled`, but this variable does not seem to be useful for this component.

**Comment by kimond** [comment]
Why do you say that this variable does not seem to be useful for this component? I'm not sure to understand.

**Comment by Cxyushi** [comment]
`keysEnabled` is a boolean variable defined in vue-virtual-scroll, which is only be used to calculate item-key for it's child components.

**Comment by kimond** [comment]
I know but we cannot change this variable through the props.

**Comment by Akryum** [comment]
This shouldn't happen anymore in the latest versions.
