### ISSUE TITLE
Weird behaviour with multiple column

### ISSUE THREAD

**Issue by daniandl** [Akryum/vue-virtual-scroller#46]
Codepen: https://codepen.io/daniandl/pen/opZGMd?editors=1111

I hardcoded the css height of the items to 60px and set item-height to 60, but the scroll container isnt filled.

The desired result is somewhat close to when setting the item-height prop to 1. Where it fills the entire container and appends when scrolling + node recycling.

Why does it display this way when passing the proper item height?
Can I make a function that tracks the height of the item and dynamically change the item-height prop? (once the proper height displays correctly)

Thanks!

**Comment by Akryum** [comment]
virtual-scroller is not compatible with multiple items per row. You can however fake this by grouping the items yourself into 'row' items.

**Comment by daniandl** [comment]
I'll just do containerHeight / itemHeight / 2 then for the item-height property. Can you confirm that I can dynamically update the prop?

**Comment by Akryum** [comment]
#64

**Comment by dungeongod** [comment]
You can create chunks for your list
ex: [1, 2, 3, 4, 5, 6, 7].chunk(3) // in lodash library
)
// [[1, 2, 3], [4, 5, 6], [7]]
Now you will get [1,2,3] in one item and can loop this in one item row.
