### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by djvonavi** [Akryum/vue-virtual-scroller#478]
Hi, Will you maintain a plugin for Vue 3?

**Comment by narenderv7** [comment]
Any update on Vue3 support?

**Comment by NathanManning** [comment]
How about now?

**Comment by m4heshd** [comment]
I don't think any of @Akryum's Vue plugins support Vue 3. I do stumble upon a lot of his stuff. Really unfortunate because these plugins are golden.

**Comment by Akryum** [comment]
Vue 3 initial version is now available with

```
yarn add vue-virtual-scroller@next
```

**Comment by Akryum** [comment]
[Docs here](https://github.com/Akryum/vue-virtual-scroller/blob/next/packages/vue-virtual-scroller/README.md)
