### ISSUE TITLE
Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by armands2ar** [Akryum/vue-virtual-scroller#49]
Got this on demo page:
https://akryum.github.io/vue-virtual-scroller/
![image](https://user-images.githubusercontent.com/9320183/35158325-6b3181fc-fd3f-11e7-888e-4432ee22e013.png)
This happens when scrolling up and down rapidly.

Originally encountered this in my own code with the errors:
![image](https://user-images.githubusercontent.com/9320183/35158416-a881984e-fd3f-11e7-91b4-c8b28837c2fc.png)

**Comment by armands2ar** [comment]
Debugging props withing slot scope reveals that itemKey in indeed blank:
![image](https://user-images.githubusercontent.com/9320183/35158702-9c43bc78-fd40-11e7-889a-779d5c8c39e3.png)
Though item does have id property with value.

And again all seems fine until scrolling quickly

**Comment by Akryum** [comment]
I could not reproduce this behavior with the latest version.

**Comment by Akryum** [comment]
Please reopen an issue if it's still an issue with 1.x
