### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by okhvr** [Akryum/vue-virtual-scroller#516]
When I change the size of the scroller, then ResizeObserver throws the error:
- "ResizeObserver loop limit exceeded" in Chrome
- "ResizeObserver loop completed with undelivered notifications." in Firefox.

This error doesn't break anything, as is written [here](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded):
> This error means that ResizeObserver was not able to deliver all observations within a single animation frame. It is benign (your site will not break).

However, I need to ignore it in my apps to avoid showing it for users and reporting in bugsnag.

The suggestion is to wrap ResizeObserver in requestAnimationFrame to avoid this error

**Comment by agaripian** [comment]
seeing this issue in our logs too
