### ISSUE TITLE
Scrolling to an item

### ISSUE THREAD

**Issue by tyio** [Akryum/vue-virtual-scroller#52]
Hi! Thanks for your work and this great component! Is it possible to scroll to a specific item in the virtual list programmatically?

I was trying to use component's method _scrollToItem(index)_, but it does not work.

`
<virtual-scroller :items="someItems" page-mode :item-height="100" ref="scroller"></virtual-scroller>
`

`
scrollTo() {
  this.$refs.scroller.scrollToItem(1000);
}
`

**Comment by tyio** [comment]
Clarified. The issue was related to wrong CSS layout.

**Comment by sopilkar** [comment]
And again, is there an official ability to scroll to an item?

**Comment by hitautodestruct** [comment]
@sopilkar I think the op is refering to an an internal method [see this code](https://github.com/Akryum/vue-virtual-scroller/blob/7223dbb110c6acad322cd6ead3c3c565604bebbb/src/components/RecycleScroller.vue#L536)
