### ISSUE TITLE
Cannot change the height of item by clicking item after rendering is complete

### ISSUE THREAD

**Issue by StingGao** [Akryum/vue-virtual-scroller#53]
ex.
```
<recycle-list class="scroller" :items="items" > 
  <template slot-scope="props"> 
    <div @click="props.item.height =50"> {{ item.value }} </div> 
  </template> 
</recycle-list>
```

**Comment by Akryum** [comment]
Did you try this example? https://github.com/Akryum/vue-virtual-scroller#exprimental-component-recyclelist

**Comment by StingGao** [comment]
@Akryum I've tried this example, and it hasn't changed.

**Comment by Akryum** [comment]
Well, it's working in the [demo](https://akryum.github.io/vue-virtual-scroller/). Make sure that your height prop is reactive (defined at the items initialization).
