### ISSUE TITLE
Is it still recommended to use functional components in recycle-list ?

### ISSUE THREAD

**Issue by asafyish** [Akryum/vue-virtual-scroller#55]
Hi,

From what I understand, functional components are cheap to create, but don't really support updates, and they are actually re-created when changed, so it seems counter intuitive to use them with recycle-list.

Is that correct ?

**Comment by Akryum** [comment]
This is correct.

**Comment by asafyish** [comment]
Is there a criteria on how to choose between using the normal virtual scroller with functional components to using the recycle-list with normal components ?

**Comment by Akryum** [comment]
`recycle-list` should generally be faster.

**Comment by asafyish** [comment]
Thanks !
