### ISSUE TITLE
Future of vue-virtual-scroller

### ISSUE THREAD

**Issue by EricRabil** [Akryum/vue-virtual-scroller#554]
Hello fellow watchers,

I'm looking for some maintainers to continue the upkeep of this library along with myself.

As we are all aware, there's been no releases or commits in this project since May. No issues or pull requests have been taken up. This is to no fault of Akryum – many of us do not pay for this software, and as such he is under no obligation to respond to these tickets.

**However,** it goes without saying there are bugs that need fixing, fixes that need merging, and features that need coding, all piling up with nobody to care for them – and all of these need oversight to make sure they're good to go into production.

I have contacted the maintainer over email to no avail, and his account looks fairly inactive. Until progress resumes on this repo, I have opened a fork at [AkryumInfinitum/vue-virtual-scroller](https://github.com/AkryumInfinitum/vue-virtual-scroller) where I will start testing and merging PRs, as well as working on issues.

As time goes on, I may take other popular projects of his that have lost steam and pull them over, which is why it is sitting in its own organization.

If anyone is interested in being a fellow maintainer of this fork, you can email me at ericjrabil@gmail.com

**Comment by LaurentChardin** [comment]
Hello eric,

I have also been fixing an internal version of it for Vue3 recently, doing only limited changes to make it work on Vue3, and probably like you, updating some dependencies as well like vue-resize.

I think it is fair to say that @Akryum is really busy on other things. 

**About vue-resize:**
He actually refreshed recently vue-resize with a alpha version on vue3. I think it would make sense to update as well the dependency in your fork. The new yarn workspace structure (monorepo) is making it cleaner to separare the test package from the main code base.

**About vue-observe-visibility:**
this one does not seem to need an update so far, i didnt have to fork it to make it work on Vue3.

**About the recent changes on your fork:**
First of all, i saw that you didn't actually made an actually github fork. I think it would have been good to keep the upstream so we could also merge it back. But right now, it is probably just a detail. 
How is the current develop branch different from the vue3 branch ? was wondering if your primary focus was the work on the Vue3 version.

Best,

**Comment by EricRabil** [comment]
Hi Laurent,

**vue3**
I'll try to give some extra attention to the vue3 branch, including adding the updated dependencies and merging the added commits from the vue3 PR.

**Meta**
I'll also look at whether I can ask GH support to attach this repo as a fork. I could always delete, fork, and force push all the new commits and branches. It'd be great for these changes to go upstream eventually.

**Comment by starkana** [comment]
Any ETA on this? Is there a current working branch for vue3?

**Comment by EricRabil** [comment]
There appears to be a Vue3 branch being worked on here https://github.com/ropez/vue-virtual-scroller

**Comment by TomDeSmet** [comment]
You can get it from here: https://www.npmjs.com/package/vue3-virtual-scroller

**Comment by starkana** [comment]
Did not work for me. Did it work for you?

**Comment by TomDeSmet** [comment]
Yes it did. I did some preliminary tests with the Recycle component only though. But I didn’t get any errors with this version. 

Still think it should be implemented/forked and maintained by Ionic though.

**Comment by guilhermeaiolfi** [comment]
Is there any actively maintained fork? Or have you guys migrated to something else? What would that be?

**Comment by EricRabil** [comment]
I ended up switching to React and using react-virtualized and react-window, which is why I stopped maintaining it. They’re a lot more mature and maintained than the virtual-scrolling libraries for Vue.

If you’re versed in React or willing to switch I recommend it for the virtualized scrolling.

-- Eric Rabil ( ***@***.*** )

Sent via Superhuman iOS ( ***@***.*** )
