### ISSUE TITLE
Scrolling is not working correctly for recycle list in page-mode

### ISSUE THREAD

**Issue by asafyish** [Akryum/vue-virtual-scroller#56]
Hi,

I noticed that when using page-mode and scrolling, the list is not being rendered, it started from commit https://github.com/Akryum/vue-virtual-scroller/commit/3596071b11526c2e702c7279e3e579400cee4fc6.

To reproduce, you can use docs-src and just add page-mode to recycle-list, and change .wrapper class to have overflow:scroll (instead of hidden).

**Comment by asafyish** [comment]
any news on this one ?

**Comment by Akryum** [comment]
I couldn't reproduce it and included the page mode toggle in the demo to show it works.
