### ISSUE TITLE
"Vue packages version mismatch" error during build

### ISSUE THREAD

**Issue by soal** [Akryum/vue-virtual-scroller#58]
### Error:

```bash
[!] (vue plugin) Error:

Vue packages version mismatch:

- vue@2.4.2
- vue-template-compiler@2.5.13
```

###  How to reproduce:
1. Clone repository
2. Run `npm install`

npm 5.4.1

**Comment by Akryum** [comment]
I'm not sure that your issue is related to vue-virtual-scroller at all.
