### ISSUE TITLE
Change scroll to index an item

### ISSUE THREAD

**Issue by iransoftnet1** [Akryum/vue-virtual-scroller#586]
I'm building a chat page
Messages that are replied must be clicked to go to that message
Or
When loading the chat, the scroll must start from the end
Or
Click on the Forward message to go to that message in the group
___
In all cases it is necessary that the scroll location is accessible to the desired item
Thanks in advance

**Comment by iransoftnet1** [comment]
I found it, thank you

```
this.$refs.list.scrollToBottom();
this.$refs.list.scrollToItem(20);
```

**Comment by haayhappen** [comment]
might be good to mention that in the docs!
