### ISSUE TITLE
Each item has a DOM element created rather item elements being re-used, causing slow FPS

### ISSUE THREAD

**Issue by jefflam** [Akryum/vue-virtual-scroller#60]
Hello, 

First off, thank you so much for creating and maintaining this library!

I'm currently having an issue where I'm trying to present > 10k items and making the scroll as smooth as possible. Looking at my output, I notice that for each item, a DOM element is created which contributes greatly to the lagginess in scroll (but still, your library makes the scroll much faster). 

I contrast this with the demo you have on the README which was able to actually 're-use' or 'replace' elements such that scrolling basically updates the elements in place with the right data, and it's not really scrolling through numerous DOM elements.

I've tried using renderers and slot-scopes and for some reason, I can't seem to get the functionality that you have in your demo to show up. 

Is there a chance you can share your demo page code? 

In addition, I implement it in a way where the data to be rendered would have to first be queried from the server, and then passed on to another componenet which then utilizes the <virtual-scroller> tag. I'm wondering if any of these steps may be causing an issue in the replacement element behaviour.

Thanks in advance!

**Comment by Akryum** [comment]
Try the `<recycle-list>` component: https://github.com/Akryum/vue-virtual-scroller#exprimental-component-recyclelist

**Comment by jefflam** [comment]
Thanks for responding @Akryum -- however it didn't work, it seems that for each item in the :Items prop that was passed in, it still created a DOM node for each of them...

**Comment by Akryum** [comment]
`<recycle-list>` recycles the component so that only the necessary ones are created. You can find the demo code here: https://github.com/Akryum/vue-virtual-scroller/blob/master/docs-src/src/App.vue#L78

**Comment by jefflam** [comment]
Thank you -- I will check it out and compare my code again and share any findings!

**Comment by jefflam** [comment]
Heya @Akryum so after much comparisons and trial and errors, I've found out that the CSS and elements surrounding the recycle-list component are all important to making it work properly. Perhaps this can be something to highlight in your guide!
