### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'accumulator' of undefined"

### ISSUE THREAD

**Issue by Baiang** [Akryum/vue-virtual-scroller#61]

**Comment by murraysum** [comment]
Just encountered this error myself when using `<virtual-scroller>`.

It would appear that if you pass an empty array of items to `<virtual-scroller` then the following error is raised:

```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'accumulator' of undefined"
```

For example if you have virtual-scroller setup as follows then:
```html
      <virtual-scroller
      class="scroller"
      :items="items"
      :renderers="renderers"
      heightField="height"
      type-field="type">
```

**Comment by Baiang** [comment]
Thanks

**Comment by Olliebaba** [comment]
@Akryum  - To work around this issue I have implemented something like:

`      <virtual-scroller
      class="scroller"
      :items="items"
      v-if="items.length"
      :renderers="renderers"
      heightField="height"
      type-field="type">`

Is there a better, built-in way to handle empty data sets to avoid this error?
