### ISSUE TITLE
Multiple items per rows

### ISSUE THREAD

**Issue by Akryum** [Akryum/vue-virtual-scroller#64]
TODO: Investigate technical solution and performance impact.

**Comment by dungeongod** [comment]
You can create chunks for your list
ex: [1, 2, 3, 4, 5, 6, 7].chunk(3)  // in lodash library
)
// [[1, 2, 3], [4, 5, 6], [7]]
Now you will get [1,2,3] in one item and can loop this in one item row.

**Comment by Shawnyeungcf** [comment]
> You can create chunks for your list ex: [1, 2, 3, 4, 5, 6, 7].chunk(3) // in lodash library ) // [[1, 2, 3], [4, 5, 6], [7]] Now you will get [1,2,3] in one item and can loop this in one item row.

`key-field` failed.

**Comment by Akryum** [comment]
Implemented with the `gridItems` and `itemSecondarySize` props
