### ISSUE TITLE
vue3-virtual-scroller 0.2.2 is broken on NPM

### ISSUE THREAD

**Issue by Tobiaqs** [Akryum/vue-virtual-scroller#654]
`node_modules/vue3-virtual-scroller/dist/vue3-virtual-scroller.esm.js` contains the following line (line 2):

```
import { ObserveVisibility } from '../../../../Users/cssr/project_ex/vue-observe-visibility/dist/vue3-observe-visibility2.esm.js';
```

This breaks the package for us.

**Comment by Akryum** [comment]
I'm sorry, I don't maintain the `vue3-virtual-scroller` package.
