### ISSUE TITLE
Broken npmjs package: vue3-virtual-scroller-0.2.2.tgz

### ISSUE THREAD

**Issue by narusas** [Akryum/vue-virtual-scroller#664]
I install from npmjs , version 0.2.2

`https://registry.npmjs.org/vue3-virtual-scroller/-/vue3-virtual-scroller-0.2.2.tgz`

vue3-virtual-scroller.esm.js file contains at line 2
```
import { ObserveVisibility } from '../../../../Users/cssr/project_ex/vue-observe-visibility/dist/vue3-observe-visibility2.esm.js';
```

It is broken to use.

**Comment by LinusBorg** [comment]
That seems to be a fork. The author of the fork appearantly didn't care to adjust the URLs or the README.

This project has a Vue 3 compatible relase as `vue-virtual-scroller@next`

https://www.npmjs.com/package/vue-virtual-scroller
