### ISSUE TITLE
alternate color?

### ISSUE THREAD

**Issue by andybeaulieu** [Akryum/vue-virtual-scroller#699]
I am trying to alternate the background-color for each item rendered in a RecycleScroller.

**Repro:**
https://codesandbox.io/s/alternate-color-with-recyclescroller-537h0

I have some CSS below, I would like every other row to be lightblue background:

.vue-recycle-scroller__item-wrapper > div:nth-child(odd) {
    background-color: lightblue;
}

**What Happens**
If you use the mousewheel or the down arrow on the scrollbar, sometimes the rows do not alternate color (I assume because the items are getting recycled out of order?)

**What Should Happen**
I am trying to get consistent alternating row color.

**Comment by Akryum** [comment]
> I assume because the items are getting recycled out of order?

Yes, you need to apply a class on items yourself, for example `:class="{ even: index % 2 === 0 }"`

**Comment by andybeaulieu** [comment]
Yup, this works fine and makes sense, thanks!
