### ISSUE TITLE
Please provide a method to access items in an item component

### ISSUE THREAD

**Issue by lichaozhy** [Akryum/vue-virtual-scroller#7]
I need to access data ``items`` used like ``props: ['item', 'items']`` in an item component.

But may be you have a reason to reject my request. So give me some help, please.

The expected source of ``Item.vue`` may looks like:

```vue
<template>
  <div class="person" @click="edit">({{item.index}}) {{item.value.name}}</div>
</template>

<script>
export default {
  props: ['item', 'items'],
  methods: {
    edit () {
      this.item.value.name += '*'
    },
  },
}
</script>
```

**Comment by Akryum** [comment]
Using [scoped slots](https://github.com/Akryum/vue-virtual-scroller#scoped-slots) you can do that:

```html
<virtual-scroller :items="items" item-height="42">
  <template scope="props">
    <my-component :items="items" />
  </template>
</virtual-scroller>
```
