### ISSUE TITLE
Items do not show page!!

### ISSUE THREAD

**Issue by snapxtp** [Akryum/vue-virtual-scroller#71]
There's a page making like this.
![drawing](https://user-images.githubusercontent.com/18392863/40770981-cda3148a-64c4-11e8-9728-3ebe7eab208a.jpeg)

Items I have added to the page have no fixed height and many variables.

Items do not show page when I make an insertion like this:
Item height requirement for using this plugins ??
Do you help with the correct method of adding a page structure as above...
`<recycle-list  page-mode :items="MyItemsArray" class="scroller"> 
        <template slot-scope="{ item, index, active }">
          <my-items-template  :itemData="item" :key="index"></my-items-template >
        </template>
</recycle-list>`

Thanks.

**Comment by Akryum** [comment]
Use `DynamicScroller` and `page-mode`.
