### ISSUE TITLE
big list with inputs performance problem

### ISSUE THREAD

**Issue by cyberm1nd** [Akryum/vue-virtual-scroller#74]
Hey!
I have to show 10.000+ rows and it's editable table (table with edit mode). Everything is perfect until i try to enter value in input - the more rows you have the harder freezes is. Digging into src i found that all array items is being deeply watched, so any input change causes in full array check and this causes hard lags. Can you please make this deep watch optional or mb find better way to do so (is it added to change height dynamically?). Removed that deep watch by myself from src and it works just fine, tho im not setting height to items dynamically.
Thanks for your work and that nice component. Best regards.
Sorry for my english :)
Edit: I do use variable height, but not setting it dynamically, got serveral types of items with different heights, but anyway problem persists even if I set itemHeight directly on root component.

**Comment by Akryum** [comment]
This shouldn't be an issue anymore with RecycleScroller and even more so with DynamicScroller.
