### ISSUE TITLE
Vue 3. `scrollToItem` not working when used in `page-mode`

### ISSUE THREAD

**Issue by brad426** [Akryum/vue-virtual-scroller#746]
When using the `vue-3` version, with the following:

```
<RecycleScroller ref="scroller" :items="items" :item-size="50" key-field="id" page-mode v-slot="{ item }">
 ...
```

calling `scroller.scrollToItem` does nothing (no errors either)
If I remove `page-mode` it works as expected

**Comment by Akryum** [comment]
Should be fixed now
