### ISSUE TITLE
Is there any way to use this component with items that the height is not known ?

### ISSUE THREAD

**Issue by darkopetreski** [Akryum/vue-virtual-scroller#75]
I have read the docs and it clearly stated that the height of the items needs to be know.

But I like to ask you directly, if there is any way, to use this component with items that the height cannot be known in advanced ?

The problem is that I am showing a book with chapters. Each chapter is shown in a card paragraph, but the height is not known. The book may have up to 2000 chapters. (each chapter is not longer then few sentences)

Rendering 2000 chapters takes up to 10-15 sec and freezes the browser. I do not like to use pagination, so I was thinking to use the virtual scroll. But the problem is that I do not know the height of the chapter in advanced because it can vary based on the text and also based on the view pot width.

So my question is, is there any way to use this component with items that the height is not know ? Maybe I can calculate the height run time ?

**Comment by Akryum** [comment]
I have a set of components and mixins that will allow you to do this, but it's not open-source yet. Soon! 😸

**Comment by darkopetreski** [comment]
That would be excellent :)

**Comment by sido420** [comment]
@Akryum updates on this?

**Comment by xerosanyam** [comment]
we definitely need this!

**Comment by patrickalima98** [comment]
any news ?

**Comment by Akryum** [comment]
Available in 1.x
