### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by TGChrisRArendt** [Akryum/vue-virtual-scroller#755]
I could have sworn there was documentation here but I don't see it. Going to the site, it redirects to this page.

**Comment by TGChrisRArendt** [comment]
Found documentation here but not sure if it's up to date https://www.npmjs.com/package/vue-virtual-scroller

**Comment by Leland** [comment]
https://github.com/Akryum/vue-virtual-scroller/tree/master/packages/vue-virtual-scroller
