### ISSUE TITLE
No items are shown - height is 0px after latest update

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [Akryum/vue-virtual-scroller#757]
### Describe the bug

After this last update, the component renders as 0px height so no items are shown.

- item-size = 72
- items are visible in dev tools

Same settings worked fine before this update

![image](https://user-images.githubusercontent.com/1735005/195970837-9712232f-fa17-41ed-bade-b4b7eb0ba8b2.png)

### Reproduction

NIL

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 14.62 GB / 31.83 GB
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Please provide a runnable reproduction thanks.

**Comment by kouts** [comment]
Hello @Akryum, first of all, thank you for this wonderful lib.
Here is CodeSandbox with the same example in `v1.0.10` and `v.1.1.0`
v1.0.10 - https://codesandbox.io/s/vue-tailwind-list-1-0-10-28tz90?file=/src/main.js
v1.1.0 - https://codesandbox.io/s/vue-tailwind-list-1-1-0-skezhr

**Comment by nipunTharuksha** [comment]
Confirming the same issue with beta. We rolled back to the alpha version.

**Comment by CharlesOkwuagwu** [comment]
> Confirming the same issue with beta. We rolled back to the alpha version.

This was on vue3 yes?

**Comment by nipunTharuksha** [comment]
Yes. Vue3. Our build was taking the latest release. Spent hours to find the issue. As soon as we saw your issue just reverted to alpha. Things working now.

**Comment by Akryum** [comment]
Should work now in 1.1.1 (Vue 2) and 2.0.0-beta.2 (Vue 3).

**Comment by kouts** [comment]
Confirming that it works with `1.1.1`, thanks @Akryum.
