### ISSUE TITLE
Lib crash if I use a different key than id and the id is null 

### ISSUE THREAD

**Issue by dragos-boisteanu** [Akryum/vue-virtual-scroller#758]
### Describe the bug

If I have a list of objects that have 2 keys like {id: null, seq: 1234} and set key-field to 'seq' the lib will crash saying there is no 'seq' field on the internal item object. 

Some screenshotos from Edge debuger
![image](https://user-images.githubusercontent.com/38045539/196279225-1fae6670-1bed-4d48-b841-8a3bd00105a0.png)
![image](https://user-images.githubusercontent.com/38045539/196279255-aca895a3-544f-47b3-bf1c-bf0455414f05.png)
![image](https://user-images.githubusercontent.com/38045539/196279283-a82b89e7-59e1-49c5-a7ea-663592efdd79.png)
![image](https://user-images.githubusercontent.com/38045539/196279415-b4e14a35-1d28-425a-856b-e1a9d9eecac4.png)

### Reproduction

Here is a repo to test https://github.com/dragos-boisteanu/scroller-issue 

If you change the id to id: i and remove key-field or set it to 'id' it will work

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 1.29 GB / 15.36 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22000.120

"dependencies": {
    "core-js": "^3.8.3",
    "vue": "^2.6.14",
    "vue-virtual-scroller": "^1.1.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "sass": "^1.32.7",
    "sass-loader": "^12.0.0",
    "vue-template-compiler": "^2.6.14"
  }
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangpf1127** [comment]
+1
