### ISSUE TITLE
Conditional rendering for items when using renderers

### ISSUE THREAD

**Issue by slim01** [Akryum/vue-virtual-scroller#76]
Is there any way to use conditional rendering with v-if for items when using virtual scroller with renderers?
And if so will the virtual scroller work as expected?

**Comment by Akryum** [comment]
Maybe you should just filter `items`.

**Comment by slim01** [comment]
Yes, if you say there is no other possibility, I have no choice.

**Comment by Akryum** [comment]
Renderers are a thing of the past now, so closing. Also, the correct answer is still filtering `items`.
