### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by AWoelfel** [Akryum/vue-virtual-scroller#772]
### Describe the bug

I use `DynamicScroller` with around 10k items. After a bit of scrolling arround i tried to select text from a view of the Items which was not possible. Items get selected in random places and in random order.

![Animation](https://user-images.githubusercontent.com/8323739/203944518-d0fc10bc-dac5-4339-9161-f8d2d8feed2c.gif)

### Reproduction

- use   `DynamicScroller`
- add items
- scroll around
- select text

### System Info

```shell
VUE: 3.2.33
vue-virtual-scroller: 2.0.0-beta.3
```

### Used Package Manager

npm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
DOM nodes order is not guaranteed as they are recycled when scrolling.

**Comment by lxjyo** [comment]
still have this proble
