### ISSUE TITLE
Dynamic scroller not handling `items` prop changes correctly

### ISSUE THREAD

**Issue by wsdimitri** [Akryum/vue-virtual-scroller#774]
### Describe the bug

Using the demo project (cloned, on the latest beta version), when filtering the dynamic scroller, previous elements are shown and overlap other items. See screenshot below:

![image](https://user-images.githubusercontent.com/65043703/206268751-b2c1f85c-a74b-4496-bc2f-0b9b0d72a9b9.png)

This is using the latest beta version `2.0.0-beta.5`. The issue is also present on `2.0.0-beta.4` but not `2.0.0-beta.3`.

It seems a recent change in beta 4 broke this functionality. 

### Reproduction

Clone the demo project and ensure vue-virtual-scroller is on the latest version.

Or, here's a StackBlitz: https://stackblitz.com/edit/vue-8g2g2k. You might have to try filtering a few times because there's 1/10th of total items due to stackblitz restrictions.  

### System Info

```shell
npmPackages:
    @vitejs/plugin-vue: ^3.1.2 => 3.2.0 
    vite: ^3.1.8 => 3.2.5 
    vue: ^3.2.41 => 3.2.45 
    vue-virtual-scroller: 2.0.0-beta.5 => 2.0.0-beta.5
```

### Used Package Manager

npm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cotillion** [comment]
We're also seeing this. Revert to beta.3 fixed it.
It seems the views are marked as nr.used = false but are still rendered.

**Comment by CharlesOkwuagwu** [comment]
> We're also seeing this. Revert to beta.3 fixed it. It seems the views are marked as nr.used = false but are still rendered.

revet to beta.4 fixed it

**Comment by CatherineAugustine** [comment]
I am using 2.0.0-beta.8 and still seeing this issue
