### ISSUE TITLE
Error: Rendered items limit reached

### ISSUE THREAD

**Issue by mathiasleroy** [Akryum/vue-virtual-scroller#78]
Hello,

I'm getting this error.

vue.min.js:6 Error: Rendered items limit reached
    at o.itemsLimitError (vue-virtual-scroller.min.js:1)
    at o.<anonymous> (vue-virtual-scroller.min.js:1)
    at Array.<anonymous> (vue.min.js:6)
    at Ke (vue.min.js:6)

Can we make the itemLimit higher  ?
I tried with 10k

**Comment by Akryum** [comment]
This means you didn't set a height on your scroller (meaning it wasn't scrolling and didn't have a scrolling viewport) so it was going to render everything at once and maybe crash your browser.

**Comment by mathiasleroy** [comment]
May I just ask where this height must be set ?
In css ? or attribute ? on which tag ?

          <virtual-scroller :items="users" :item-height="itemHeight" keyField="id" containerClass="xxx" contentClass="row">
            <template slot-scope="props">
              <custom-card :d="props.item"/>
            </template>
          </virtual-scroller>

Thanks!

**Comment by Akryum** [comment]
As [described in the docs](https://github.com/Akryum/vue-virtual-scroller#usage), you need to set a CSS height on the virtual scroller.

**Comment by martinhbramwell** [comment]
I am also hitting this issue, if I have more than 1000 data items:

```
[Vue warn]: Error in nextTick: "Error: Rendered items limit reached"

found in

---> <VirtualScroller> at /home/akryum/Projets/vue-virtual-scroller/src/components/VirtualScroller.vue
       <Test> at src/components/Distributor/Bottle/Test.vue
         <BaseLayer> at src/components/MainLayout/BaseLayer.vue
           <App> at src/App.vue
             <Root>
Error: Rendered items limit reached
    at VueComponent.itemsLimitError (vue-virtual-scroller.esm.js?f232:578)
    at VueComponent.eval (vue-virtual-scroller.esm.js?f232:772)
    at Array.eval (vue.esm.js?efeb:1837)
    at flushCallbacks (vue.esm.js?efeb:1758)
```

The annoying thing is that I am copying exactly the code from the Alligator.io article [Performant Lists and Tables in Vue.js with vue-virtual-scroller](https://alligator.io/vuejs/vue-virtual-scroller/). 1000 items works as expected, but 1001 ==> BOOM.
```
<template>
  <virtual-scroller :items="items" item-height="42" container-tag="table" content-tag="tbody">
    <thead slot="before-content">
      <tr>
        <td>Age</td>
        <td>Name</td>
        <td>Company</td>
      </tr>
    </thead>
    <template slot-scope="props">
      <tr :key="props.itemKey">
        <td>{{props.item.age}}</td>
        <td>{{props.item.name}}</td>
        <td>{{props.item.company}}</td>
      </tr>
    </template>
  </virtual-scroller>
</template>

<script>
import items from './data.json';

export default {
  data: () => ({
    items,
  }),
};
</script>
```
When I examine the element with Chrome dev tools, I see:

```
.virtual-scroller[data-v-caa2d078]:not(.page-mode) {
    overflow-y: auto;
}
```

So I seem to be doing what is required.  I do see `overflow-y: auto;` inherited from the `.html` element of my CSS framework (Bulma) but it should not have priority, correct?

Can you suggest debugging action I could take to figure out why this happening?
When you say, "(meaning it wasn't scrolling and didn't have a scrolling viewport)" should I be seeing **two** scroll bars, one for the main layout and a 2nd one for the data table?

Thanks.
