### ISSUE TITLE
Cursor jumps to random para

### ISSUE THREAD

**Issue by xerosanyam** [Akryum/vue-virtual-scroller#81]
Use vue-scroller to scroll through a list of paragraphs. These are the problems I face
1. Each paragraph contains different number of words. Hence I cannot use variable as well as fixed height mode. If I try to use variable mode, I don't understand how I can calculate height of paragraph
2. when I keep pressing down key inside a paragraph, it jumps to a random paragraph at some instant.

**Comment by Akryum** [comment]
1. Use the new DynamicScroller
2. See #93
