### ISSUE TITLE
Doesn't project maintained anymore?

### ISSUE THREAD

**Issue by tastytea-github** [Akryum/vue-virtual-scroller#813]
### Describe the bug

The last update was 5 months ago despite of 178 opened issues and 15 pull requests. Doesn't it mean the project is not maintained anymore? I cannot see even any discussions in the latest issues.

### Reproduction

-

### System Info

```shell
-
```

### Used Package Manager

npm

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Akryum/vue-virtual-scroller/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Please use the discussions for that kind of thread. Thanks
