### ISSUE TITLE
Items spacing in grid mode

### ISSUE THREAD

**Issue by yevhendevbox** [Akryum/vue-virtual-scroller#843]
### Clear and concise description of the problem

Hi there, using virtual scroller with grid mode, stack on how to change space/gap between items in grid? 

### Suggested solution

Any tips or help is highly appreciate!

### Validations

- [X] Read the [docs](https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md).
- [X] Check that there isn't [already an issue](https://github.com/Akryum/vue-virtual-scroller/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Thunder7991** [comment]
hello ， How did you achieve it?
