### ISSUE TITLE
table tbody content issue

### ISSUE THREAD

**Issue by kimlisa** [Akryum/vue-virtual-scroller#87]
Hello, I am trying to build a 2,000 item row table. The following works perfectly:
```
<virtual-scroller :items="sortedKeys" item-height="50" class="scroller" contentTag="table" contentClass="table table-condensed table-hover">
	<template slot-scope="props">
		<tr :key="props.itemKey" :item-index="props.itemIndex" class="item">
			<td v-for="(prop, index) in arrSymProps" :key="'P' + index">stuff here</td>
		</tr>
	</template>
</virtual-scroller>
```

Now I need to add my table headers. But when I try to make my containerTag="table" contentTag="tbody" as below:
```
<virtual-scroller :items="sortedKeys" item-height="50" class="scroller" containerTag="table" contentTag="tbody" containerClass="table table-condensed table-hover">
	<thead slot="before-content">
		<tr>
			<th>header stuff here</th
		</tr>
	</thead>
	<template slot-scope="props">
		<tr :key="props.itemKey" :item-index="props.itemIndex" class="item">
			<td v-for="(prop, index) in arrSymProps" :key="'P' + index">stuff here</td>
		</tr>
	</template>
</virtual-scroller>
```

I run into height issues. My 50px "item-height" becomes what looks like 600px, so each of my tr (table-row) height is way too big. I can get a decent size down by setting "item-height" to 5, but either way I run into jumpy scrolling issues and scroller jumping backwards and not being able to move forward.

What am I doing wrong? I only get this issue when I try to insert tbody tag into my content.
My tbody does not have any special height set to it (not that I see in my inspection page).

**Comment by kimlisa** [comment]
I played around with div tables, and display: table, or display: table-row-group gives me the same issues. Also, even though I set my div containerClass="someName1" and contentClass="someName2", if the CSS for "someName1" and "someName2" is scoped in my .vue file, the styles are not applied, unless globally applied.

**Comment by nekosaur** [comment]
I've been running into the same problem. It can be observed in this sandbox https://codesandbox.io/s/9v1m0vlx4

@kimlisa The class issue could be a deep selector thing since you're using scoped styles

**Comment by Vuchan** [comment]
Same issue, nobody answer? 😄

**Comment by lauri865** [comment]
Same issue, introduced in 0.11.7. Works fine before that.

**Comment by Akryum** [comment]
See #116
