### ISSUE TITLE
not working with inline-template

### ISSUE THREAD

**Issue by pfleu** [Akryum/vue-virtual-scroller#89]
I want to use the component I made with virtual-scroller with different pages in my app, so I made my component dynamic. I need to change the template with twig in my views, so I have tried to externalize the template by using "inline template", but virtual-scroll doesn't work anymore. Is it possible to use inline-template ?
I changed the example code sandbox to show what I want to do:
https://codesandbox.io/s/l21x309q0z?module=%2Findex.html
I'm new to Vue so I might be missing something obvious.

**Comment by Akryum** [comment]
Please reopen an issue if you still have problems with 1.0
