### ISSUE TITLE
How to pass custom props to scroller items? 

### ISSUE THREAD

**Issue by kovart** [Akryum/vue-virtual-scroller#9]
Are there any ways to pass my custom props to the scroller items?

**Comment by kovart** [comment]
So, I found how to do this. I used shared variables which I "require" from my controller file
`
<template>
   {{ shared.yourProps }}
</template>
<script>
var controller = require('./controller.js');
module.exports = { 
   data: {
       shared: controller.shared
   }
 }
</script>
`

**Comment by Akryum** [comment]
You can also use [scoped slots](https://github.com/Akryum/vue-virtual-scroller#scoped-slots). For example:

```html
<virtual-scroller :items="items" item-height="42">
  <template scope="props">
    <my-component :any-prop="props.item.someProp" />
  </template>
</virtual-scroller>
```
