### ISSUE TITLE
Images are not rendered correctly when using variable height mode

### ISSUE THREAD

**Issue by theniceangel** [Akryum/vue-virtual-scroller#95]
In dynamic scroller demo, variable height is caused by different item content, and each item has a fixed avatar, but we often need to attach variable height images in each item, and it will render incorrectly, because item content is rendered in nextTick, we can not ensure images acting like content.

**Comment by Akryum** [comment]
Use a `loaded` boolean, and put it in the size dependencies of
DynamicScrollerItemm.

**Comment by theniceangel** [comment]
Thanks, I will have a try

**Comment by Den2016** [comment]
i try <img @load="item.loaded = true"... /> and put dependecies, but if i scroll down and back to top, loaded already true, but image reloads from cache and row size is incorrect. How do I know that the image has left the pool and has been loaded again?

**Comment by Den2016** [comment]
random saves us )))
<img @load="item.loaded = Math.random().toString(36).substring(7)" :src="item.preview" 
solve this problem ))

**Comment by kamaladenalhomsi** [comment]
@Den2016 
It works
Thanks for sharing this.
