### ISSUE TITLE
Only last item visible

### ISSUE THREAD

**Issue by karatekaneen** [Akryum/vue-virtual-scroller#96]
First of all, thank you for the work you're doing. Really appreciate it.

Anyhow, when updating to the new version and trying to change over to dynamicScroller I get it to scroll smoothly but only the last item (or at least I think it's the last one) is visible. So obviously I'm missing something but I can't find what it is.
Worth mentioning is that when I'm scrolling down really fast I can see glimpses of the items but when I scroll back up they're not there anymore.

Here's my implementation:
```
<DynamicScroller
style="height: 75vh"
:items="dataToDisplay" 
:min-item-height="200">
	<template slot-scope="{ item, index, active }">
		<DynamicScrollerItem
		:item="item"
		:active="active"
		:data-index="index">
		
		    <v-card
		    style="margin: 10px 0px;"
		    class="rw-card card-hover">
			<v-card-actions
			 style="float: right;">
				<v-spacer/>
				<v-btn icon	flat color="error" @click="exclude(item)">
					<v-icon>close</v-icon>
				</v-btn>
			 </v-card-actions>
	                 <!--- .... all the card content here... -->
		     </v-card>
		</DynamicScrollerItem>
	</template>
</DynamicScroller>
```

And importing the components as:
```
import { DynamicScroller } from 'vue-virtual-scroller'
import { DynamicScrollerItem } from 'vue-virtual-scroller'

export default {
	  props: ["input"],
	  components:{
		  DynamicScroller: DynamicScroller,
		  DynamicScrollerItem: DynamicScrollerItem
	  },
```

Anyone got an idea of what I'm doing wrong?

Addon 1:
After further investigation it seems like it's rendering but outside of the viewport.
So if i set `height: 50%` on the scroller i can scroll down and get one element showed and if using pagemode and then scrolling on the page I can scroll down and see everything but one element at the time, so somehow only one item is active.

**Comment by karatekaneen** [comment]
Also, if setting 
```
.scroller {
	height: 100%;
	overflow-y: auto;
}
```
as in examples I get:
```
11:05:22,423 It seems the scroller element isn't scrolling, so it tries to render all the items at once. Scroller: 
<div class="vue-recycle-scroller scroller ready">
vue-virtual-scroller.esm.js:632
11:05:22,426 Make sure the scroller has a fixed height and 'overflow-y' set to 'auto' so it can scroll correctly and only render the items visible in the scroll viewport.
vue-virtual-scroller.esm.js:633
```

**Comment by levine404** [comment]
I'm having the same exact issue!

**Comment by petersutter** [comment]
me too, and I'm using the RecycleScroller

**Comment by namotco** [comment]
Also having this issue, but only shows the 1st element.

**Comment by amatakasap** [comment]
> keyField (default: 'id'): field used to identify items and optimize render views management.

The "key" of your item

`
<dynamic-scroller
  :items="items"
  :min-item-height="100"
  :key-field="key">
</dynamic-scroller
`

**Comment by guushamann** [comment]
an example that works after reading the comment of amatakasap, you have to set :key-field
[example](https://codesandbox.io/s/50650j7wml)

**Comment by radireddy** [comment]
I am having the same issue with RecycleScroller.

<template>
<recycle-scroller class="scroller" :items="hotels" :item-height="240" key-field="ID">
      <div slot-scope="{ item, index }" class="card">
        <div class="row">
          <div class="col-8">
            <div class="pos-relative">
              <h3>{{item.DisplayName}} {{index}}</h3>
            </div>
          </div>
        </div>
      </div>
    </recycle-scroller>
</template>

<script>
import { mapState } from 'vuex';
import { RecycleScroller } from 'vue-virtual-scroller';

export default {

  components: {
    'recycle-scroller': RecycleScroller,
  },

  computed: mapState({
    hotels: state => state.items.items,
  }),
};
</script>

<style>
.scroller {
  height: 100%;
}

.card {
  height: 240%;
}
</style>

**Comment by BloodSucker123** [comment]
Hope some knows how to fix this issue, cause even though I use the example code whitch is from the doc-src, about  RecycleScroller and it shows no list of items, but the example usage only shows 1 item.
Can someone pinpoint what this issue caused? also the ` key-field="ID"` that is being mentioned is not working.

**Comment by dmitriykorobkov** [comment]
Same issue on both, `RecycleScroller` and `DynamicScroller`

**Comment by BloodSucker123** [comment]
You have to work with the height of the wrapper

**Comment by ShoshinNikita** [comment]
I had the same issue. I fixed it by adding field `id` into objects

**Before:**

```js
items = [
  { test: 1, help: 3 },
  { test: 2, help: 4 },
  { test: 3, help: 5 },
  { test: 4, help: 6 },
  { test: 5, help: 7 },
  { test: 6, help: 8 }
]
```

**After:**

```js
items = [
  { id: 0, test: 1, help: 3 },
  { id: 1, test: 2, help: 4 },
  { id: 2, test: 3, help: 5 },
  { id: 3, test: 4, help: 6 },
  { id: 4, test: 5, help: 7 },
  { id: 5, test: 6, help: 8 }
]
```

**Comment by caweidmann** [comment]
Adding `id` also worked for me. Thanks!

**Comment by varadekd** [comment]
I am still facing the same issue

**Comment by legolaserea** [comment]
you need set  unique identification for your each 'item', just like the 'key' in Vue's 'v-for'. The key-field default is 'id' , which refer to your item's id property, You can also set other  identification in your item as the 'key' , only need to set the key-filed refer to it.

**Comment by iamvitali** [comment]
Is there a way to just use the index as a `:key-field`? My data doesn't always have unique data points like a primary key, but obviously every row is unique... So essentially using the key/index would be ideal.

**Comment by bhargavr445** [comment]
> an example that works after reading the comment of amatakasap, you have to set :key-field
> [example](https://codesandbox.io/s/50650j7wml)

<img width="855" alt="Screen Shot 2020-09-11 at 12 36 18 AM" src="https://user-images.githubusercontent.com/20152194/92861573-aaee3200-f3c7-11ea-8270-713a8e616eaf.png">
Thanks for the link, but when I add page mode to your component it is not rendering all the elements as expected

**Comment by JasonBai007** [comment]
> I had the same issue. I fixed it by adding field `id` into objects
> 
> **Before:**
> 
> ```js
> items = [
>   { test: 1, help: 3 },
>   { test: 2, help: 4 },
>   { test: 3, help: 5 },
>   { test: 4, help: 6 },
>   { test: 5, help: 7 },
>   { test: 6, help: 8 }
> ]
> ```
> 
> **After:**
> 
> ```js
> items = [
>   { id: 0, test: 1, help: 3 },
>   { id: 1, test: 2, help: 4 },
>   { id: 2, test: 3, help: 5 },
>   { id: 3, test: 4, help: 6 },
>   { id: 4, test: 5, help: 7 },
>   { id: 5, test: 6, help: 8 }
> ]
> ```

solved my problem.
