### ISSUE TITLE
I don't see the reason for the existence of this component

### ISSUE THREAD

**Issue by AlexandraK** [Akryum/vue-virtual-scroller#98]
So, I was looking for a virtual scroller type component, and i found this. Demos appear to show exactly what someone needs when looking for a virtual scroller, but after using it you realise that it's not.

Why? Because it doesn't work with variable heights, even tho it says that it does. 
In reality it doesn't because you still need to provide the height one way or another. And most, if not all real-world use cases involve variable heights!

The dynamic scroller is supposed to work without defined heights, but it doesn't because it will show the list items scaled to min-item-height, so it's useless.

I understand that computing the actual CSS height is not effective because of performance reasons, but then why lie about what you can and cannot do?

The only way to implement a scroller with variable-height items, is to implement the scrollbar as well and use the list length as reference for the list height and scrollbar handle, instead of the item heights. Sure it won't be perfect but it's way better then computing css heights, or having fixed heights that leave spaces of different sizes, depending on the device you are browsing on.

**Comment by Akryum** [comment]
> Demos appear to show exactly what someone needs when looking for a virtual scroller

It does.

> Why? Because it doesn't work with variable heights

Again, it does.

> The dynamic scroller is supposed to work without defined heights

That's right! Like in the demo! Incredible.

> but then why lie about what you can and cannot do?

Maybe next time you don't understand how to use a library, ask questions and help improve documentation instead of just saying the author is lying to you.
